import type { LoopStage } from './types';

/** Central interactive engineering loop — Roadmap 2.0. */
export const engineeringLoop: readonly LoopStage[] = [
  {
    id: 'problem',
    label: 'Проблема',
    engineer:
      'Формулирует проблему, пользователя и ограничения — не feature request as-is.',
    knowledge: [
      'Формулирование проблемы',
      'Допущения',
      'Ограничения',
      'Корневая причина',
    ],
    aiTools: ['Research briefs', 'Проверка допущений', 'Скан конкурентов'],
    humanMustVerify: [
      'Проблема реальна',
      'Scope не раздут',
      'Kill criteria есть',
    ],
    typicalMistakes: [
      'IDEA = PROBLEM',
      'Строить без пользователя',
      'Скрытые assumptions',
    ],
    mission: 'Написать one-pager: user + problem + non-goals.',
  },
  {
    id: 'research',
    label: 'Исследование',
    engineer: 'Собирает контекст: существующие решения, данные, риски.',
    knowledge: ['Методы исследования', 'Метрики', 'Prior art'],
    aiTools: [
      'Суммаризация документов',
      'Сравнение вариантов',
      'Извлечение trade-offs',
    ],
    humanMustVerify: ['Источники', 'Bias', 'Что неизвестно'],
    typicalMistakes: ['Только мнения AI', 'Нет границ исследования'],
    mission: 'Собрать research note с 3 вариантами и gaps.',
  },
  {
    id: 'decompose',
    label: 'Декомпозиция',
    engineer: 'Делит работу на границы: product / UX / data / API / risk.',
    knowledge: ['Декомпозиция', 'Зависимости', 'Интерфейсы'],
    aiTools: ['Разбиение работ', 'Предложения по зависимостям'],
    humanMustVerify: ['Нет скрытых связей', 'Порядок работ осмыслен'],
    typicalMistakes: ['Слишком мелкие задачи', 'Всё в один PR'],
    mission: 'Разложить задачу на 5–9 work packages с owners (human/AI).',
  },
  {
    id: 'design',
    label: 'Дизайн',
    engineer: 'Проектирует UX и architecture до кода.',
    knowledge: ['UX-потоки', 'Границы', 'Режимы отказа', 'ADR'],
    aiTools: ['Черновики потоков', 'Варианты архитектуры', 'Черновики ADR'],
    humanMustVerify: ['Trade-offs', 'Обратимость', 'Границы безопасности'],
    typicalMistakes: ['Дизайн во время кодинга', 'Архитектура ради моды'],
    mission: 'Выбрать архитектуру из 2–3 AI вариантов и зафиксировать ADR.',
  },
  {
    id: 'build',
    label: 'Сборка',
    engineer: 'Реализует vertical slice; AI — основной executor под review.',
    knowledge: ['Frontend/Backend/DB/API', 'Контракты', 'Состояния'],
    aiTools: ['Scaffold', 'Реализация', 'Рефакторинг', 'Объяснение'],
    humanMustVerify: ['Корректность', 'Границы', 'Нет посторонних изменений'],
    typicalMistakes: ['Принять код без понимания', 'Scope creep mid-build'],
    mission: 'Собрать working slice с понятными слоями.',
  },
  {
    id: 'verify',
    label: 'Проверка',
    engineer: 'Делает качество executable: tests, static checks, review.',
    knowledge: ['Пирамида тестов', 'Тестирование по риску', 'Контракты'],
    aiTools: ['Генерация тестов', 'Отчёты о качестве', 'Триаж сбоев'],
    humanMustVerify: ['Coverage по риску', 'False greens', 'Security basics'],
    typicalMistakes: ['Только happy path', 'AI tests без assertions'],
    mission: 'Получить quality report и закрыть top risks.',
  },
  {
    id: 'deploy',
    label: 'Деплой',
    engineer: 'Доставляет изменение с smoke и rollback.',
    knowledge: ['CI/CD', 'Окружения', 'Secrets'],
    aiTools: ['Черновик CI', 'Release notes', 'Smoke-чек-листы'],
    humanMustVerify: ['Secrets', 'Rollback', 'Smoke после деплоя'],
    typicalMistakes: ['Деплой без observability', 'Prod = laptop'],
    mission: 'Задеплоить с smoke proof.',
  },
  {
    id: 'observe',
    label: 'Наблюдение',
    engineer: 'Смотрит logs/metrics/traces/errors — failures visible.',
    knowledge: ['Триада observability', 'Алерты'],
    aiTools: ['Суммаризация инцидентов', 'Корреляция сигналов'],
    humanMustVerify: ['Сигнал vs шум', 'Влияние на пользователя'],
    typicalMistakes: ['Нет alerts', 'Логи без context'],
    mission: 'Показать один реальный сигнал ошибки end-to-end.',
  },
  {
    id: 'measure',
    label: 'Измерение',
    engineer: 'Связывает technical и product metrics.',
    knowledge: ['CWV', 'Latency', 'Activation/retention'],
    aiTools: ['Предложения метрик', 'Черновики анализа воронки'],
    humanMustVerify: ['Метрика отвечает на вопрос', 'Нет vanity metrics'],
    typicalMistakes: ['Оптимизация без baseline'],
    mission: 'Зафиксировать baseline до оптимизации.',
  },
  {
    id: 'learn',
    label: 'Обучение',
    engineer: 'Делает выводы: что сработало, что нет, что автоматизировать.',
    knowledge: ['Postmortems', 'Гипотезы'],
    aiTools: ['Черновики выводов', 'Сравнение результатов'],
    humanMustVerify: ['Честные failures', 'Actionable next steps'],
    typicalMistakes: ['Blame без системного исправления'],
    mission: 'Короткий learning log после цикла.',
  },
  {
    id: 'improve',
    label: 'Улучшение',
    engineer: 'Вносит улучшение системы, не только фичи.',
    knowledge: ['Техдолг', 'Границы рефакторинга'],
    aiTools: ['Предложения рефакторинга', 'Оценки влияния'],
    humanMustVerify: ['ROI', 'Риск регрессии'],
    typicalMistakes: ['Rewrite ради rewrite'],
    mission: 'Одно improvement с измеримым эффектом.',
  },
  {
    id: 'automate',
    label: 'Автоматизация',
    engineer: 'Убирает repetitive work; защищает human attention.',
    knowledge: ['Скрипты', 'Агенты', 'Self-check'],
    aiTools: ['Черновики автоматизаций', 'Workflow агентов'],
    humanMustVerify: ['Путь отказа', 'Risk gates', 'Permissions'],
    typicalMistakes: ['Автоматизация без verification'],
    mission: 'Автоматизировать один repetitive workflow с verify.',
  },
] as const;

export const engineeringCore = [
  'СИСТЕМНОЕ МЫШЛЕНИЕ',
  'РЕШЕНИЕ ПРОБЛЕМ',
  'AI',
  'ВЕРИФИКАЦИЯ',
  'АВТОМАТИЗАЦИЯ',
  'БЕЗОПАСНОСТЬ',
  'ПРОИЗВОДИТЕЛЬНОСТЬ',
  'ПРОДУКТОВОЕ МЫШЛЕНИЕ',
  'ПРИНЯТИЕ РЕШЕНИЙ',
  'КОММУНИКАЦИЯ',
] as const;

export const masterSpine = [
  'СПЕЦИАЛИСТ',
  'ФУНДАМЕНТ',
  'ИНТЕГРАЦИЯ',
  'ИНЖЕНЕРИЯ',
  'AI-ОРКЕСТРИРОВАННАЯ ИНЖЕНЕРИЯ',
  'НЕИЗВЕСТНАЯ ТЕРРИТОРИЯ',
  '∞',
] as const;

export const uxQuestions = [
  'ЧТО МНЕ НУЖНО ПОНЯТЬ?',
  'ЧТО Я МОГУ СОБРАТЬ?',
  'ЧТО Я МОГУ ПРОВЕРИТЬ?',
  'ЧТО Я МОГУ АВТОМАТИЗИРОВАТЬ?',
  'ЧТО Я МОГУ ДЕЛЕГИРОВАТЬ AI?',
  'ЧТО Я ВСЁ ЕЩЁ ДОЛЖЕН КОНТРОЛИРОВАТЬ?',
] as const;

export const endModel = [
  'ЗНАНИЕ',
  'СПОСОБНОСТЬ',
  'МИССИЯ',
  'РЕАЛЬНАЯ СИСТЕМА',
  'ВЕРИФИКАЦИЯ',
  'АВТОМАТИЗАЦИЯ',
  'ОРКЕСТРАЦИЯ',
  'ИНЖЕНЕРНАЯ СИСТЕМА',
  'НЕИЗВЕСТНОЕ',
  'УЧИТЬСЯ СНОВА',
] as const;
