import type { LoopStage } from './types';

/** Central interactive engineering loop — Roadmap 2.0. */
export const engineeringLoop: readonly LoopStage[] = [
  {
    id: 'problem',
    label: 'PROBLEM',
    engineer: 'Формулирует проблему, пользователя и ограничения — не feature request as-is.',
    knowledge: ['Problem framing', 'Assumptions', 'Constraints', 'Root cause'],
    aiTools: ['Research briefs', 'Assumption challenges', 'Competitor scan'],
    humanMustVerify: ['Проблема реальна', 'Scope не раздут', 'Kill criteria есть'],
    typicalMistakes: ['IDEA = PROBLEM', 'Строить без пользователя', 'Скрытые assumptions'],
    mission: 'Написать one-pager: user + problem + non-goals.',
  },
  {
    id: 'research',
    label: 'RESEARCH',
    engineer: 'Собирает контекст: существующие решения, данные, риски.',
    knowledge: ['Research methods', 'Metrics', 'Prior art'],
    aiTools: ['Summarize docs', 'Compare options', 'Extract trade-offs'],
    humanMustVerify: ['Источники', 'Bias', 'Что неизвестно'],
    typicalMistakes: ['Только мнения AI', 'Нет границ исследования'],
    mission: 'Собрать research note с 3 вариантами и gaps.',
  },
  {
    id: 'decompose',
    label: 'DECOMPOSE',
    engineer: 'Делит работу на границы: product / UX / data / API / risk.',
    knowledge: ['Decomposition', 'Dependencies', 'Interfaces'],
    aiTools: ['Work breakdown', 'Dependency suggestions'],
    humanMustVerify: ['Нет скрытых связей', 'Порядок работ осмыслен'],
    typicalMistakes: ['Слишком мелкие задачи', 'Всё в один PR'],
    mission: 'Разложить задачу на 5–9 work packages с owners (human/AI).',
  },
  {
    id: 'design',
    label: 'DESIGN',
    engineer: 'Проектирует UX и architecture до кода.',
    knowledge: ['UX flows', 'Boundaries', 'Failure modes', 'ADRs'],
    aiTools: ['Draft flows', 'Architecture options', 'ADR drafts'],
    humanMustVerify: ['Trade-offs', 'Reversibility', 'Security boundaries'],
    typicalMistakes: ['Design while coding', 'Fashion-driven architecture'],
    mission: 'Выбрать архитектуру из 2–3 AI вариантов и зафиксировать ADR.',
  },
  {
    id: 'build',
    label: 'BUILD',
    engineer: 'Реализует vertical slice; AI — основной executor под review.',
    knowledge: ['Frontend/Backend/DB/API', 'Contracts', 'States'],
    aiTools: ['Scaffold', 'Implement', 'Refactor', 'Explain'],
    humanMustVerify: ['Correctness', 'Boundaries', 'No unrelated changes'],
    typicalMistakes: ['Принять код без понимания', 'Scope creep mid-build'],
    mission: 'Собрать working slice с понятными слоями.',
  },
  {
    id: 'verify',
    label: 'VERIFY',
    engineer: 'Делает качество executable: tests, static checks, review.',
    knowledge: ['Pyramid', 'Risk-based testing', 'Contracts'],
    aiTools: ['Generate tests', 'Quality reports', 'Failure triage'],
    humanMustVerify: ['Coverage по риску', 'False greens', 'Security basics'],
    typicalMistakes: ['Только happy path', 'AI tests без assertions'],
    mission: 'Получить quality report и закрыть top risks.',
  },
  {
    id: 'deploy',
    label: 'DEPLOY',
    engineer: 'Доставляет изменение с smoke и rollback.',
    knowledge: ['CI/CD', 'Environments', 'Secrets'],
    aiTools: ['Draft CI', 'Release notes', 'Smoke checklists'],
    humanMustVerify: ['Secrets', 'Rollback', 'Smoke after deploy'],
    typicalMistakes: ['Deploy without observability', 'Prod = laptop'],
    mission: 'Задеплоить с smoke proof.',
  },
  {
    id: 'observe',
    label: 'OBSERVE',
    engineer: 'Смотрит logs/metrics/traces/errors — failures visible.',
    knowledge: ['Observability triad', 'Alerts'],
    aiTools: ['Summarize incidents', 'Correlate signals'],
    humanMustVerify: ['Signal vs noise', 'User impact'],
    typicalMistakes: ['Нет alerts', 'Логи без context'],
    mission: 'Показать один реальный сигнал ошибки end-to-end.',
  },
  {
    id: 'measure',
    label: 'MEASURE',
    engineer: 'Связывает technical и product metrics.',
    knowledge: ['CWV', 'Latency', 'Activation/retention'],
    aiTools: ['Metric proposals', 'Funnel analysis drafts'],
    humanMustVerify: ['Метрика отвечает на вопрос', 'Нет vanity metrics'],
    typicalMistakes: ['Optimize without baseline'],
    mission: 'Зафиксировать baseline до оптимизации.',
  },
  {
    id: 'learn',
    label: 'LEARN',
    engineer: 'Делает выводы: что сработало, что нет, что автоматизировать.',
    knowledge: ['Postmortems', 'Hypotheses'],
    aiTools: ['Draft learnings', 'Compare outcomes'],
    humanMustVerify: ['Честные failures', 'Actionable next steps'],
    typicalMistakes: ['Blame without system fix'],
    mission: 'Короткий learning log после цикла.',
  },
  {
    id: 'improve',
    label: 'IMPROVE',
    engineer: 'Вносит улучшение системы, не только фичи.',
    knowledge: ['Tech debt', 'Refactor boundaries'],
    aiTools: ['Propose refactors', 'Impact estimates'],
    humanMustVerify: ['ROI', 'Regression risk'],
    typicalMistakes: ['Rewrite ради rewrite'],
    mission: 'Одно improvement с измеримым эффектом.',
  },
  {
    id: 'automate',
    label: 'AUTOMATE',
    engineer: 'Убирает repetitive work; защищает human attention.',
    knowledge: ['Scripts', 'Agents', 'Self-check'],
    aiTools: ['Draft automations', 'Agent workflows'],
    humanMustVerify: ['Failure path', 'Risk gates', 'Permissions'],
    typicalMistakes: ['Automation without verification'],
    mission: 'Автоматизировать один repetitive workflow с verify.',
  },
] as const;

export const engineeringCore = [
  'SYSTEM THINKING',
  'PROBLEM SOLVING',
  'AI',
  'VERIFICATION',
  'AUTOMATION',
  'SECURITY',
  'PERFORMANCE',
  'PRODUCT THINKING',
  'DECISION MAKING',
  'COMMUNICATION',
] as const;

export const masterSpine = [
  'SPECIALIST',
  'FOUNDATION',
  'INTEGRATION',
  'ENGINEERING',
  'AI-ORCHESTRATED ENGINEERING',
  'UNKNOWN TERRITORY',
  '∞',
] as const;

export const uxQuestions = [
  'WHAT DO I NEED TO UNDERSTAND?',
  'WHAT CAN I BUILD?',
  'WHAT CAN I VERIFY?',
  'WHAT CAN I AUTOMATE?',
  'WHAT CAN I DELEGATE TO AI?',
  'WHAT MUST I STILL CONTROL?',
] as const;

export const endModel = [
  'KNOWLEDGE',
  'CAPABILITY',
  'MISSION',
  'REAL SYSTEM',
  'VERIFICATION',
  'AUTOMATION',
  'ORCHESTRATION',
  'ENGINEERING SYSTEM',
  'UNKNOWN',
  'LEARN AGAIN',
] as const;
