import type { Mission } from '../types';

export const engineeringMissions: readonly Mission[] = [
  {
    id: 'eng-mission-design',
    code: 'MISSION 13',
    title: 'Design for failure and scale',
    kind: 'mission',
    month: 13,
    objective: 'Спроектировать систему с явными failure modes и scale breakpoints.',
    understand: ['Trade-offs at 10 / 1K / 100K / 1M', 'DETECT→PREVENT'],
    build: ['System diagram', 'Failure playbook', 'Bottleneck notes'],
    aiCanHelp: ['Propose topologies', 'Stress-test assumptions', 'Draft failure scenarios'],
    mustVerify: ['Trade-offs explicit', 'Recovery path exists', 'Cost considered'],
    doneWhen: ['Design review pack ready'],
  },
  {
    id: 'eng-mission-agents',
    code: 'MISSION 14',
    title: 'Design agent architecture',
    kind: 'mission',
    month: 14,
    objective: 'Спроектировать agent stack: roles, tools, permissions, termination.',
    understand: ['Agent vs workflow vs autonomous', 'When specialization hurts'],
    build: ['Agent map', 'Permission model', 'Validation loop'],
    aiCanHelp: ['Draft contracts', 'Simulate handoffs'],
    mustVerify: ['Boundaries clear', 'No unnecessary agents'],
    doneWhen: ['Agent architecture ADR approved by you'],
  },
  {
    id: 'eng-mission-automate',
    code: 'MISSION 15',
    title: 'Automation audit + ROI',
    kind: 'mission',
    month: 15,
    objective: 'Найти repetitive work и оценить VALUE = Frequency × Time Saved × Reliability.',
    understand: ['Self-healing risk', 'What must stay human'],
    build: ['Audit list', 'ROI ranking', '≥3 automations with verify path'],
    aiCanHelp: ['Inventory tasks', 'Draft scripts/agents'],
    mustVerify: ['Failure handling', 'Attention savings measured'],
    doneWhen: ['Automation backlog prioritized'],
  },
  {
    id: 'eng-mission-product',
    code: 'MISSION 16',
    title: 'Problem discovery before build',
    kind: 'mission',
    month: 16,
    objective: 'Доказать: IDEA ≠ PROBLEM, FEATURE ≠ VALUE.',
    understand: ['Hypotheses', 'Validation', 'Product↔engineering coupling'],
    build: ['Problem brief', 'Experiment plan', 'Success metrics'],
    aiCanHelp: ['Research', 'Competitor scan', 'Draft hypotheses'],
    mustVerify: ['Root problem named', 'Kill criteria exist'],
    doneWhen: ['Decision to build / not build is evidence-based'],
  },
  {
    id: 'eng-mission-lead',
    code: 'MISSION 17',
    title: 'Lead an engineering decision',
    kind: 'mission',
    month: 17,
    objective: 'QUESTION→CONTEXT→OPTIONS→TRADE-OFFS→DECISION→CONSEQUENCES.',
    understand: ['Scope', 'Risk', 'Stakeholder communication'],
    build: ['Decision record', 'AI brief', 'Delivery plan'],
    aiCanHelp: ['Option matrix', 'Draft docs', 'Devil’s advocate'],
    mustVerify: ['You can defend the decision simply'],
    doneWhen: ['ADR + plan accepted by you as owner'],
  },
  {
    id: 'eng-capstone',
    code: 'CAPSTONE',
    title: 'Build a real product',
    kind: 'final',
    month: 18,
    objective: 'Самостоятельно выбрать проблему и создать настоящий продукт — не tutorial project.',
    understand: ['Full lifecycle', 'Multi-agent org design', 'Attention as scarce resource'],
    build: [
      'Product + UX + architecture',
      'Deep frontend + production backend/data/API',
      'QA/security/performance/devops/observability/analytics',
      'Multi-agent workflow + automation',
    ],
    aiCanHelp: ['Entire agent team under contracts', 'Docs', 'Verification loops'],
    mustVerify: [
      'Which agents are necessary (and which are not)',
      'Human intent/context/judgement remain',
      'Cycle repeats after deploy',
    ],
    doneWhen: ['Product live', 'Engineering OS documented', 'Learn→Improve→Automate loop running'],
  },
  {
    id: 'eng-final-boss',
    code: 'FINAL BOSS',
    title: 'Build your own engineering system',
    kind: 'boss',
    month: 18,
    objective:
      'Система берёт feature request и проходит большую часть пути сама — human Define/Review/Approve/Decide.',
    understand: ['Risk-gated autonomy', 'Verification architecture'],
    build: [
      'Feature → analysis → spec → architecture → impl → tests → security → PR → CI → deploy → monitor',
    ],
    aiCanHelp: ['Pipeline agents', 'Quality gates', 'Monitoring summaries'],
    mustVerify: ['Critical actions need human control', 'Self-check before auto-accept'],
    doneWhen: ['Demo of feature request through the system'],
  },
] as const;

export const engineeringMissionById = Object.fromEntries(
  engineeringMissions.map((mission) => [mission.id, mission]),
) as Readonly<Record<string, Mission>>;
