import type { Mission } from '../types';

export const integrationMissions: readonly Mission[] = [
  {
    id: 'int-mission-01',
    code: 'MISSION 01',
    title: 'Architect the product',
    kind: 'mission',
    month: 7,
    objective: 'Из product idea получить Requirements + UX + Architecture + Data Model + API.',
    understand: ['Boundaries', 'Trade-offs', 'Data flow', 'Failure handling'],
    build: ['Requirements', 'UX sketch', 'Architecture diagram', 'Data model', 'API outline'],
    aiCanHelp: ['Propose 3 architectures', 'Draft requirements', 'Challenge assumptions'],
    mustVerify: ['Инженер выбирает архитектуру', 'Trade-offs записаны', 'Out-of-scope ясен'],
    doneWhen: ['Пакет готов к build', 'AI variants compared by you'],
  },
  {
    id: 'int-mission-02',
    code: 'MISSION 02',
    title: 'Build full stack',
    kind: 'mission',
    month: 8,
    objective: 'Next.js + Backend + PostgreSQL + REST + GraphQL как связанная система.',
    understand: ['Service boundaries', 'Contracts', 'Migrations', 'Cache/async triggers'],
    build: [
      'Modular backend',
      'Schema + indexes',
      'REST + GraphQL demo',
      'Resilient frontend states',
    ],
    aiCanHelp: ['Scaffold services', 'Draft migrations', 'Generate contract tests'],
    mustVerify: ['Каждый слой объясним', 'Authz не магия', 'Нет secrets в repo'],
    doneWhen: ['Vertical slice работает end-to-end'],
  },
  {
    id: 'int-mission-03',
    code: 'MISSION 03',
    title: 'Quality system',
    kind: 'mission',
    month: 10,
    objective: 'Unit + Integration + E2E + static checks + security как executable quality.',
    understand: ['Pyramid', 'Risk-based coverage', 'Quality gates'],
    build: ['Test plan', 'Automated suite', 'Lint/type/contract checks', 'Security scan path'],
    aiCanHelp: ['Generate test plan', 'Draft tests', 'Summarize failures into quality report'],
    mustVerify: ['Gates блокируют bad merge', 'Report читаем человеком'],
    doneWhen: ['CI fails on red quality', 'Есть human-readable report'],
  },
  {
    id: 'int-mission-04',
    code: 'MISSION 04',
    title: 'Productionize',
    kind: 'boss',
    month: 11,
    objective: 'Docker + CI/CD + deploy + monitoring + alerts.',
    understand: ['Environments', 'Smoke tests', 'Logs/metrics/traces', 'Rollback'],
    build: ['Pipeline', 'Deployed env', 'Dashboards/alerts sketch', 'Runbook stub'],
    aiCanHelp: ['Draft CI', 'Suggest alert thresholds', 'Incident checklist'],
    mustVerify: ['Detect path существует', 'Secrets isolated', 'Smoke after deploy'],
    doneWhen: ['Prod-like URL + visible failure signal'],
  },
  {
    id: 'int-mission-05',
    code: 'MISSION 05',
    title: 'Automate repetitive workflows',
    kind: 'mission',
    month: 12,
    objective: 'Найти минимум 5 repetitive workflows и сдвинуть их вниз по automation ladder.',
    understand: ['What can be scripted / AI / self-checked'],
    build: ['Automation map', '≥5 automated workflows', 'Failure handling notes'],
    aiCanHelp: ['Inventory repetitive work', 'Draft scripts/agents', 'Propose verification'],
    mustVerify: ['Automation has failure path', 'Human still owns approval where needed'],
    doneWhen: ['5 workflows automated with verification notes'],
  },
  {
    id: 'int-capstone',
    code: 'CAPSTONE',
    title: 'Product v2 + multi-agent workflow',
    kind: 'final',
    month: 12,
    objective:
      'Превратить Foundation product в production-like system и собрать AI engineering workflow с handoffs.',
    understand: [
      'Garbage in → garbage out',
      'Agent contracts',
      'Context engineering',
      'Verification 2.0',
    ],
    build: [
      'Product v2 requirements pack',
      'Full stack production slice',
      'Quality + DevOps + observability',
      'Multi-agent pipeline with human review',
    ],
    aiCanHelp: [
      'Research',
      'Product/architect agents',
      'Implementation agents',
      'QA/security/devops agents',
      'Docs',
    ],
    mustVerify: [
      'Agents не ломают систему друг другу',
      'Human approval gates',
      'Responsibility matrix explicit',
    ],
    doneWhen: ['System ships', 'Workflow documented', 'Ready for Phase III orchestration'],
  },
] as const;

export const integrationMissionById = Object.fromEntries(
  integrationMissions.map((mission) => [mission.id, mission]),
) as Readonly<Record<string, Mission>>;
