import type { IntegrationOverview } from '../types';

export const integrationOverview: IntegrationOverview = {
  title: 'INTEGRATION',
  subtitle: 'Connect engineering disciplines into one coherent system.',
  lead: 'От breadth к integration: соединять части в систему, делегировать AI-агентам execution и оставлять responsibility человеку.',
  stats: [
    { label: 'MONTHS', value: '6' },
    { label: 'WEEKS', value: '26' },
    { label: 'H / WEEK', value: '10' },
    { label: 'FOCUS', value: 'SYSTEMS' },
    { label: 'AI', value: 'AGENTS' },
    { label: 'CAPSTONE', value: 'v2' },
  ],
  integrationFlow: [
    'PRODUCT',
    'UX',
    'ARCHITECTURE',
    'FRONTEND ↔ API ↔ BACKEND',
    'DATABASE',
    'TESTING',
    'CI/CD + SECURITY',
    'OBSERVABILITY',
    'ANALYTICS',
    'IMPROVEMENT',
  ],
  progress: [
    { id: 'systems', label: 'Systems thinking', coverage: 100 },
    { id: 'production', label: 'Production engineering', coverage: 78 },
    { id: 'agents', label: 'Agent orchestration', coverage: 62 },
    { id: 'automation', label: 'Automation', coverage: 48 },
    { id: 'capstone', label: 'Product v2', coverage: 30 },
  ],
  leverage: [
    { id: 'manual', label: 'Manual Work', coverage: 72 },
    { id: 'assisted', label: 'AI Assisted', coverage: 55 },
    { id: 'automated', label: 'Automated', coverage: 38 },
    { id: 'agentic', label: 'Agentic', coverage: 24 },
    { id: 'selfcheck', label: 'Self-checking', coverage: 14 },
  ],
  philosophy: {
    lines: [
      "Don't just build features. Design systems.",
      "Don't just use AI. Orchestrate AI.",
      "Don't just automate tasks. Automate workflows.",
      "Don't just test outputs. Design systems that verify themselves.",
    ],
    sequence: ['SKILLS', 'SYSTEMS', 'AGENTS', 'WORKFLOWS', 'AUTOMATION'],
  },
  transition: {
    title: 'FROM INTEGRATION TO ENGINEERING',
    body: 'Ты умеешь соединять дисциплины в систему. Следующий шаг — проектировать системы, где большая часть инженерной работы выполняется AI.',
    steps: ['UNDERSTAND', 'INTEGRATE', 'ORCHESTRATE', 'AUTOMATE', 'AUTONOMOUS ENGINEERING'],
    cta: 'ENTER PHASE III',
  },
  finalState: {
    title: 'AI-AUGMENTED ENGINEER',
    deep: 'FRONTEND',
    broad: [
      'PRODUCT',
      'ARCHITECTURE',
      'BACKEND',
      'DATABASE',
      'API',
      'QA',
      'DEVOPS',
      'SECURITY',
      'PERFORMANCE',
      'ANALYTICS',
    ],
    ai: ['AGENT ORCHESTRATION', 'AUTOMATION'],
    note: 'Responsibility remains human even when execution becomes automated.',
  },
};
