import type { IntegrationOverview } from '../types';

export const integrationOverview: IntegrationOverview = {
  title: 'ИНТЕГРАЦИЯ',
  subtitle: 'Соедини инженерные дисциплины в одну согласованную систему.',
  lead: 'От широты к интеграции: соединять части в систему, делегировать AI-агентам исполнение и оставлять ответственность человеку.',
  stats: [
    { label: 'МЕСЯЦЫ', value: '6' },
    { label: 'НЕДЕЛИ', value: '26' },
    { label: 'Ч / НЕДЕЛЯ', value: '10' },
    { label: 'ФОКУС', value: 'СИСТЕМЫ' },
    { label: 'AI', value: 'АГЕНТЫ' },
    { label: 'CAPSTONE', value: 'v2' },
  ],
  integrationFlow: [
    'ПРОДУКТ',
    'UX',
    'АРХИТЕКТУРА',
    'FRONTEND ↔ API ↔ BACKEND',
    'БАЗА ДАННЫХ',
    'ТЕСТИРОВАНИЕ',
    'CI/CD + SECURITY',
    'НАБЛЮДАЕМОСТЬ',
    'АНАЛИТИКА',
    'УЛУЧШЕНИЕ',
  ],
  progress: [
    { id: 'systems', label: 'Системное мышление', coverage: 100 },
    { id: 'production', label: 'Production-инженерия', coverage: 78 },
    { id: 'agents', label: 'Оркестрация агентов', coverage: 62 },
    { id: 'automation', label: 'Автоматизация', coverage: 48 },
    { id: 'capstone', label: 'Продукт v2', coverage: 30 },
  ],
  leverage: [
    { id: 'manual', label: 'Вручную', coverage: 72 },
    { id: 'assisted', label: 'С помощью AI', coverage: 55 },
    { id: 'automated', label: 'Автоматизировано', coverage: 38 },
    { id: 'agentic', label: 'Агентное', coverage: 24 },
    { id: 'selfcheck', label: 'Самопроверка', coverage: 14 },
  ],
  philosophy: {
    lines: [
      'Не просто строй фичи. Проектируй системы.',
      'Не просто используй AI. Оркестрируй AI.',
      'Не просто автоматизируй задачи. Автоматизируй процессы.',
      'Не просто тестируй результаты. Проектируй системы, которые проверяют себя сами.',
    ],
    sequence: ['НАВЫКИ', 'СИСТЕМЫ', 'АГЕНТЫ', 'ПРОЦЕССЫ', 'АВТОМАТИЗАЦИЯ'],
  },
  transition: {
    title: 'ОТ ИНТЕГРАЦИИ К ИНЖЕНЕРИИ',
    body: 'Ты умеешь соединять дисциплины в систему. Следующий шаг — проектировать системы, где большая часть инженерной работы выполняется AI.',
    steps: [
      'ПОНИМАТЬ',
      'ИНТЕГРИРОВАТЬ',
      'ОРКЕСТРИРОВАТЬ',
      'АВТОМАТИЗИРОВАТЬ',
      'АВТОНОМНАЯ ИНЖЕНЕРИЯ',
    ],
    cta: 'ПЕРЕЙТИ К PHASE III',
  },
  finalState: {
    title: 'AI-AUGMENTED ENGINEER',
    deep: 'FRONTEND',
    broad: [
      'ПРОДУКТ',
      'АРХИТЕКТУРА',
      'BACKEND',
      'БАЗА ДАННЫХ',
      'API',
      'QA',
      'DEVOPS',
      'БЕЗОПАСНОСТЬ',
      'ПРОИЗВОДИТЕЛЬНОСТЬ',
      'АНАЛИТИКА',
    ],
    ai: ['ОРКЕСТРАЦИЯ АГЕНТОВ', 'АВТОМАТИЗАЦИЯ'],
    note: 'Ответственность остаётся за человеком, даже когда исполнение автоматизировано.',
  },
};
