import type { Domain } from '../types';

export const foundationDomains: readonly Domain[] = [
  {
    id: 'product',
    pillar: 'think',
    title: 'Продукт',
    short: 'Проблема → ценность → scope',
    why: 'Код без проблемы — это хобби. Инженер начинает с пользователя, ценности и ограничений.',
    aiLeverage:
      'Исследовать альтернативы, набросать PRD, оспорить assumptions, предложить срезы MVP.',
    outcome: 'Умеешь превратить идею в структурированную продуктовую задачу.',
    topics: [
      'Формулировка проблемы',
      'Требования',
      'Продуктовое мышление',
      'Потребности пользователя',
      'Бизнес-цели',
      'Приоритизация',
      'Ограничения',
    ],
    whatGoodLooksLike: [
      'Ясная проблема',
      'Названный пользователь',
      'Ограниченный MVP',
      'Явные trade-offs',
    ],
    depth: {
      summary: 'Продуктовое мышление — ось THINK.',
      detail:
        'Ты формулируешь проблему, пользователя, ценность, требования и границы MVP до того, как открыть редактор.',
      know: [
        'Формулировка проблемы',
        'Требования',
        'Приоритизация',
        'Ограничения',
      ],
      able: [
        'Написать one-pager',
        'Вырезать MVP',
        'Аргументировать trade-offs',
      ],
      ai: ['Исследование', 'Черновик требований', 'Стресс-тест assumptions'],
    },
  },
  {
    id: 'analysis',
    pillar: 'think',
    title: 'Анализ',
    short: 'Гипотезы → доказательства',
    why: 'Решения без метрик и root cause — гадание. Анализ связывает продукт и инженерию.',
    aiLeverage:
      'Сравнивать варианты, находить аномалии, структурировать RCA, предлагать метрики.',
    outcome:
      'Принимаешь data-aware решения и умеешь искать причину, а не симптом.',
    topics: [
      'Технический анализ',
      'Продуктовый анализ',
      'Метрики',
      'Гипотезы',
      'Data-driven решения',
      'Root cause analysis',
    ],
    whatGoodLooksLike: [
      'Сначала гипотеза',
      'Измеримые сигналы',
      'Root cause, не blame',
    ],
    depth: {
      summary: 'Анализ — мост между идеей и архитектурой.',
      detail: 'Гипотезы, метрики, RCA и технические trade-offs до реализации.',
      know: ['Метрики', 'Гипотезы', 'RCA'],
      able: ['Сформулировать гипотезу', 'Выбрать метрики', 'Провести RCA'],
      ai: ['Сравнить варианты', 'Набросать деревья RCA', 'Предложить метрики'],
    },
  },
  {
    id: 'ux-ui',
    pillar: 'think',
    title: 'UX / UI',
    short: 'Удобство by design',
    why: 'Интерфейс — часть системы. Инженер отличает хороший UX от красивого шума.',
    aiLeverage:
      'UX-критика, альтернативные flows, черновики wireframe, a11y-ревью.',
    outcome: 'Проектируешь понятные flows и оцениваешь UI без роли «дизайнер».',
    topics: [
      'Юзабилити',
      'Информационная архитектура',
      'Interaction design',
      'Design systems',
      'Accessibility',
      'Визуальная иерархия',
      'Оценка UX',
    ],
    whatGoodLooksLike: [
      'Понятно',
      'Предсказуемо',
      'Согласовано',
      'Доступно',
      'Быстро',
      'Прощает ошибки',
    ],
    depth: {
      summary: 'UX/UI — ответственность инженера, не «чужая зона».',
      detail:
        'Flows, когнитивная нагрузка, иерархия, состояния, a11y и design tokens.',
      know: ['User flow', 'Иерархия', 'Основы a11y', 'Empty/error states'],
      able: ['Нарисовать flow', 'Оценить UI', 'Проверить keyboard path'],
      ai: ['Критика', 'Альтернативные flows', 'Чеклист a11y'],
    },
  },
  {
    id: 'frontend',
    pillar: 'build',
    title: 'Frontend',
    short: 'Глубокая специализация',
    why: 'Твоя глубина. Но frontend — не вся Phase I: он якорь, а не поглотитель roadmap.',
    aiLeverage:
      'Компоненты, рефакторинг, тесты, гипотезы по performance — всегда с проверкой.',
    outcome: 'Глубокий frontend + понимание границ с API и backend.',
    topics: [
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Модели рендеринга',
      'State',
      'Data fetching',
      'Performance',
      'Accessibility',
      'Тестирование',
    ],
    technologies: [
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
    ],
    whatGoodLooksLike: [
      'Типизировано',
      'Доступно',
      'Достаточно быстро',
      'Тестируемо',
      'Ясные границы',
    ],
    depth: {
      summary: 'Frontend — deep track внутри BUILD.',
      detail:
        'JS/TS, React, Next.js, state, data fetching, a11y и performance — без монополизации фазы.',
      know: ['Модели рендеринга', 'Границы state', 'Паттерны fetching'],
      able: [
        'Собрать production UI',
        'Оптимизировать осознанно',
        'Покрыть тестами',
      ],
      ai: ['Scaffold', 'Рефакторинг', 'Генерация тестов', 'Объяснение кода'],
    },
  },
  {
    id: 'backend',
    pillar: 'build',
    title: 'Backend',
    short: 'Рабочая компетенция',
    why: 'Интерфейс — только край системы. Нужно понимать, что происходит после request.',
    aiLeverage:
      'Генерировать endpoints, ревьюить слои, набрасывать validation, дебажить API.',
    outcome: 'Спроектировать и собрать небольшой backend с понятными слоями.',
    topics: [
      'Сервер',
      'Runtime',
      'Routes',
      'Services',
      'Бизнес-логика',
      'Validation',
      'Ошибки',
      'Auth',
      'Authorization',
    ],
    technologies: ['Node.js', 'HTTP', 'Validation', 'Auth'],
    whatGoodLooksLike: [
      'Ясные границы',
      'Validation',
      'Обработка ошибок',
      'Безопасность',
      'Observability',
      'Тесты',
      'Performance',
    ],
    depth: {
      summary: 'Backend competence без смены профессии.',
      detail:
        'Server, routes, services, validation, errors, auth — и объяснение каждого слоя.',
      know: ['Слои', 'Validation', 'Authn/Authz', 'Модель ошибок'],
      able: ['CRUD API', 'Защитить routes', 'Документировать API'],
      ai: ['Scaffold services', 'Ревью границ', 'Генерация тестов'],
    },
  },
  {
    id: 'api',
    pillar: 'build',
    title: 'API',
    short: 'REST · GraphQL · HTTP',
    why: 'API — контракт между людьми и системами. Семантика HTTP важнее фреймворка.',
    aiLeverage:
      'Моделировать ресурсы, набрасывать схемы, сравнивать trade-offs REST vs GraphQL.',
    outcome: 'Умеешь выбрать и обосновать REST или GraphQL для задачи.',
    topics: [
      'Моделирование ресурсов',
      'Endpoints',
      'Семантика HTTP',
      'Пагинация',
      'Фильтрация',
      'Версионирование',
      'GraphQL schema',
      'Resolvers',
    ],
    technologies: ['REST', 'GraphQL', 'OpenAPI'],
    whatGoodLooksLike: [
      'Согласованные ресурсы',
      'Честные status codes',
      'Документированные контракты',
    ],
    depth: {
      summary: 'API как явный контракт.',
      detail:
        'REST semantics + GraphQL model — понимать различия и trade-offs.',
      know: ['HTTP methods/status', 'Дизайн ресурсов', 'Основы GraphQL'],
      able: [
        'Спроектировать REST',
        'Описать GraphQL schema',
        'Аргументировать выбор',
      ],
      ai: ['Черновик OpenAPI', 'Предложить schema', 'Найти несогласованности'],
    },
  },
  {
    id: 'database',
    pillar: 'build',
    title: 'База данных',
    short: 'PostgreSQL · моделирование',
    why: 'Данные переживают UI. Модель и индексы определяют правду системы.',
    aiLeverage:
      'Предлагать schema, миграции, индексы — проверять через EXPLAIN и constraints.',
    outcome:
      'Спроектировать схему, связи, миграции и базовые запросы в PostgreSQL.',
    topics: [
      'Таблицы',
      'Связи',
      'Ключи',
      'Индексы',
      'Joins',
      'Транзакции',
      'Нормализация',
      'Миграции',
    ],
    technologies: ['SQL', 'PostgreSQL'],
    whatGoodLooksLike: [
      'Явная схема',
      'Целостность',
      'Индексы на hot paths',
      'Миграции возможны',
    ],
    depth: {
      summary: 'PostgreSQL как основной ориентир.',
      detail:
        'Моделирование, ключи, индексы, транзакции, миграции — без DBA-сертификации.',
      know: ['Связи', 'Индексы', 'Транзакции'],
      able: ['Нарисовать ER', 'Написать миграции', 'Объяснить join'],
      ai: ['Черновик schema', 'Предложить индексы', 'Ревью N+1'],
    },
  },
  {
    id: 'architecture',
    pillar: 'build',
    title: 'Архитектура',
    short: 'Границы · trade-offs',
    why: 'Архитектура — про зависимости и эволюцию, а не про коллекцию patterns.',
    aiLeverage:
      'Сравнивать варианты, проводить границы, стресс-тестить coupling — выбор за человеком.',
    outcome: 'Объясняешь, почему система устроена именно так.',
    topics: [
      'Separation of concerns',
      'Модульность',
      'Coupling',
      'Cohesion',
      'Границы',
      'Слои',
      'Масштабируемость',
      'Поддерживаемость',
      'Trade-offs',
    ],
    whatGoodLooksLike: [
      'Просто',
      'Явно',
      'Модульно',
      'Тестируемо',
      'Наблюдаемо',
      'Эволюционируемо',
    ],
    depth: {
      summary: 'Почему слои существуют.',
      detail:
        'UI → Application → Domain → Infrastructure → Database и альтернативы.',
      know: ['Границы', 'Coupling/cohesion', 'Направление зависимостей'],
      able: ['Нарисовать слои', 'Назвать trade-offs', 'Упростить систему'],
      ai: ['Матрица вариантов', 'Критика границ'],
    },
  },
  {
    id: 'qa',
    pillar: 'operate',
    title: 'QA',
    short: 'Думай как тестировщик',
    why: 'Качество — инженерная дисциплина, не бюрократия после merge.',
    aiLeverage: 'Генерировать сценарии — инженер оценивает покрытие и риск.',
    outcome: 'Строишь mental model: happy / alt / edge / invalid / recovery.',
    topics: [
      'Дизайн тестов',
      'Функциональное тестирование',
      'Регрессия',
      'Edge cases',
      'Unit',
      'Integration',
      'E2E',
      'Mocks',
      'Тестовые данные',
    ],
    whatGoodLooksLike: [
      'По риску',
      'С учётом пирамиды',
      'Воспроизводимо',
      'Автоматизация там, где окупается',
    ],
    depth: {
      summary: 'QA mindset внутри OPERATE.',
      detail: 'Сценарии, пирамида тестов, exploratory и quality gates.',
      know: ['Уровни тестов', 'Edge cases', 'Assertions'],
      able: ['Написать unit/integration/E2E', 'Составить matrix сценариев'],
      ai: [
        'Генерировать кейсы',
        'Предложить fixtures',
        'Никогда не пропускать human review',
      ],
    },
  },
  {
    id: 'devops',
    pillar: 'operate',
    title: 'DevOps',
    short: 'Доставляй с уверенностью',
    why: '«Works on my machine» — red flag. Инженер доводит до среды и наблюдаемости.',
    aiLeverage:
      'Черновики Dockerfile/CI — проверяй secrets, envs и путь rollback.',
    outcome: 'Собрать CI, контейнер и деплой небольшого продукта.',
    topics: [
      'Git',
      'CI/CD',
      'Docker',
      'Среды',
      'Secrets',
      'Логирование',
      'Мониторинг',
      'Карта cloud',
    ],
    technologies: ['Git', 'Docker', 'CI/CD', 'AWS concepts'],
    whatGoodLooksLike: [
      'Воспроизводимые сборки',
      'Безопасные secrets',
      'Наблюдаемые деплои',
    ],
    depth: {
      summary: 'Доставка и среды.',
      detail:
        'Git → build → lint → test → deploy; Docker; staging/prod; cloud map без сертификации.',
      know: ['Этапы pipeline', 'Контейнеры', 'Env/secrets'],
      able: ['Написать Dockerfile', 'Настроить CI', 'Задеплоить'],
      ai: ['Черновик CI', 'Объяснить сбои', 'Ревью Dockerfile'],
    },
  },
  {
    id: 'security',
    pillar: 'operate',
    title: 'Безопасность',
    short: 'Думай как атакующий',
    why: 'Security — не afterthought. Trust boundaries проходят через весь стек.',
    aiLeverage:
      'Threat-промпты, чеклист-ревью — никогда не вставляй secrets в промпты.',
    outcome: 'Проводишь базовый security review небольшого продукта.',
    topics: [
      'Authentication',
      'Authorization',
      'Secrets',
      'HTTPS',
      'Validation',
      'OWASP mindset',
      'XSS',
      'CSRF',
      'SQLi',
      'CORS',
    ],
    whatGoodLooksLike: [
      'Least privilege',
      'Валидированный input',
      'Нет secrets в репо',
      'HTTPS везде',
    ],
    depth: {
      summary: 'Безопасность across the stack.',
      detail: 'INPUT → TRUST? → VALIDATE → SANITIZE → AUTHORIZE → EXECUTE.',
      know: ['Authn/Authz', 'Типичные vulns', 'Гигиена secrets'],
      able: [
        'Threat-model MVP',
        'Исправить XSS/CSRF-класс проблем',
        'Ревью deps',
      ],
      ai: [
        'Чеклист',
        'Объяснить пути атаки',
        'Не доверяй сгенерированному auth вслепую',
      ],
    },
  },
  {
    id: 'performance',
    pillar: 'operate',
    title: 'Производительность',
    short: 'Измерь → измени → измерь',
    why: 'Never optimize blindly. Сначала bottleneck, потом гипотеза.',
    aiLeverage: 'Гипотезы и планы профилирования — решают цифры.',
    outcome: 'Умеешь измерить, найти узкое место и проверить изменение.',
    topics: [
      'Core Web Vitals',
      'Размер бандла',
      'Кэширование',
      'N+1',
      'Latency',
      'Throughput',
      'Профилирование',
    ],
    whatGoodLooksLike: [
      'Измерено',
      'На гипотезах',
      'Заметные пользователю выигрыши',
    ],
    depth: {
      summary: 'Цикл performance.',
      detail: 'Measure → bottleneck → hypothesis → change → measure again.',
      know: ['CWV', 'Драйверы latency на backend', 'Инвалидация кэша'],
      able: ['Профилировать', 'Убрать N+1', 'Улучшить LCP/INP'],
      ai: ['Предложить эксперименты', 'Интерпретировать traces'],
    },
  },
] as const;

export const domainById = Object.fromEntries(
  foundationDomains.map((domain) => [domain.id, domain]),
) as Readonly<Record<string, Domain>>;
