import type { Domain } from '../types';

export const foundationDomains: readonly Domain[] = [
  {
    id: 'product',
    pillar: 'think',
    title: 'Product',
    short: 'Problem → value → scope',
    why: 'Код без проблемы — это хобби. Инженер начинает с пользователя, ценности и ограничений.',
    aiLeverage: 'Research alternatives, draft PRDs, challenge assumptions, generate MVP cuts.',
    outcome: 'Умеешь превратить идею в структурированную продуктовую задачу.',
    topics: [
      'Problem framing',
      'Requirements',
      'Product thinking',
      'User needs',
      'Business goals',
      'Prioritization',
      'Constraints',
    ],
    whatGoodLooksLike: ['Clear problem', 'Named user', 'Scoped MVP', 'Explicit trade-offs'],
    depth: {
      summary: 'Продуктовое мышление — ось THINK.',
      detail:
        'Ты формулируешь проблему, пользователя, ценность, требования и границы MVP до того, как открыть редактор.',
      know: ['Problem framing', 'Requirements', 'Prioritization', 'Constraints'],
      able: ['Написать one-pager', 'Вырезать MVP', 'Аргументировать trade-offs'],
      ai: ['Research', 'Draft requirements', 'Stress-test assumptions'],
    },
  },
  {
    id: 'analysis',
    pillar: 'think',
    title: 'Analysis',
    short: 'Hypotheses → evidence',
    why: 'Решения без метрик и root cause — гадание. Анализ связывает продукт и инженерию.',
    aiLeverage: 'Compare options, find anomalies, structure RCA, propose metrics.',
    outcome: 'Принимаешь data-aware решения и умеешь искать причину, а не симптом.',
    topics: [
      'Technical analysis',
      'Product analysis',
      'Metrics',
      'Hypotheses',
      'Data-driven decisions',
      'Root cause analysis',
    ],
    whatGoodLooksLike: ['Hypothesis first', 'Measurable signals', 'Root cause, not blame'],
    depth: {
      summary: 'Анализ — мост между идеей и архитектурой.',
      detail: 'Гипотезы, метрики, RCA и технические trade-offs до реализации.',
      know: ['Metrics', 'Hypotheses', 'RCA'],
      able: ['Сформулировать гипотезу', 'Выбрать метрики', 'Провести RCA'],
      ai: ['Compare options', 'Draft RCA trees', 'Suggest metrics'],
    },
  },
  {
    id: 'ux-ui',
    pillar: 'think',
    title: 'UX / UI',
    short: 'Usable by design',
    why: 'Интерфейс — часть системы. Инженер отличает хороший UX от красивого шума.',
    aiLeverage: 'UX critique, alternative flows, wireframe drafts, a11y review.',
    outcome: 'Проектируешь понятные flows и оцениваешь UI без роли «дизайнер».',
    topics: [
      'Usability',
      'Information architecture',
      'Interaction design',
      'Design systems',
      'Accessibility',
      'Visual hierarchy',
      'UX evaluation',
    ],
    whatGoodLooksLike: ['Clear', 'Predictable', 'Consistent', 'Accessible', 'Fast', 'Forgiving'],
    depth: {
      summary: 'UX/UI — ответственность инженера, не «чужая зона».',
      detail: 'Flows, когнитивная нагрузка, иерархия, состояния, a11y и design tokens.',
      know: ['User flow', 'Hierarchy', 'A11y basics', 'Empty/error states'],
      able: ['Нарисовать flow', 'Оценить UI', 'Проверить keyboard path'],
      ai: ['Critique', 'Alt flows', 'A11y checklist'],
    },
  },
  {
    id: 'frontend',
    pillar: 'build',
    title: 'Frontend',
    short: 'Deep specialization',
    why: 'Твоя глубина. Но frontend — не вся Phase I: он якорь, а не поглотитель roadmap.',
    aiLeverage: 'Components, refactors, tests, performance hypotheses — always verified.',
    outcome: 'Глубокий frontend + понимание границ с API и backend.',
    topics: [
      'JavaScript',
      'TypeScript',
      'React',
      'Next.js',
      'Rendering models',
      'State',
      'Data fetching',
      'Performance',
      'Accessibility',
      'Testing',
    ],
    technologies: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Next.js'],
    whatGoodLooksLike: ['Typed', 'Accessible', 'Fast enough', 'Testable', 'Clear boundaries'],
    depth: {
      summary: 'Frontend — deep track внутри BUILD.',
      detail:
        'JS/TS, React, Next.js, state, data fetching, a11y и performance — без монополизации фазы.',
      know: ['Rendering models', 'State boundaries', 'Fetching patterns'],
      able: ['Собрать production UI', 'Оптимизировать осознанно', 'Покрыть тестами'],
      ai: ['Scaffold', 'Refactor', 'Generate tests', 'Explain code'],
    },
  },
  {
    id: 'backend',
    pillar: 'build',
    title: 'Backend',
    short: 'Working competence',
    why: 'Интерфейс — только край системы. Нужно понимать, что происходит после request.',
    aiLeverage: 'Generate endpoints, review layers, draft validation, debug APIs.',
    outcome: 'Спроектировать и собрать небольшой backend с понятными слоями.',
    topics: [
      'Server',
      'Runtime',
      'Routes',
      'Services',
      'Business logic',
      'Validation',
      'Errors',
      'Auth',
      'Authorization',
    ],
    technologies: ['Node.js', 'HTTP', 'Validation', 'Auth'],
    whatGoodLooksLike: [
      'Clear boundaries',
      'Validation',
      'Error handling',
      'Security',
      'Observability',
      'Tests',
      'Performance',
    ],
    depth: {
      summary: 'Backend competence без смены профессии.',
      detail: 'Server, routes, services, validation, errors, auth — и объяснение каждого слоя.',
      know: ['Layers', 'Validation', 'Authn/Authz', 'Error model'],
      able: ['CRUD API', 'Protect routes', 'Document API'],
      ai: ['Scaffold services', 'Review boundaries', 'Generate tests'],
    },
  },
  {
    id: 'api',
    pillar: 'build',
    title: 'API',
    short: 'REST · GraphQL · HTTP',
    why: 'API — контракт между людьми и системами. Семантика HTTP важнее фреймворка.',
    aiLeverage: 'Model resources, draft schemas, compare REST vs GraphQL trade-offs.',
    outcome: 'Умеешь выбрать и обосновать REST или GraphQL для задачи.',
    topics: [
      'Resource modelling',
      'Endpoints',
      'HTTP semantics',
      'Pagination',
      'Filtering',
      'Versioning',
      'GraphQL schema',
      'Resolvers',
    ],
    technologies: ['REST', 'GraphQL', 'OpenAPI'],
    whatGoodLooksLike: ['Consistent resources', 'Honest status codes', 'Documented contracts'],
    depth: {
      summary: 'API как явный контракт.',
      detail: 'REST semantics + GraphQL model — понимать различия и trade-offs.',
      know: ['HTTP methods/status', 'Resource design', 'GraphQL basics'],
      able: ['Спроектировать REST', 'Описать GraphQL schema', 'Аргументировать выбор'],
      ai: ['Draft OpenAPI', 'Propose schema', 'Review inconsistencies'],
    },
  },
  {
    id: 'database',
    pillar: 'build',
    title: 'Database',
    short: 'PostgreSQL · modelling',
    why: 'Данные переживают UI. Модель и индексы определяют правду системы.',
    aiLeverage: 'Suggest schema, migrations, indexes — verify with EXPLAIN and constraints.',
    outcome: 'Спроектировать схему, связи, миграции и базовые запросы в PostgreSQL.',
    topics: [
      'Tables',
      'Relations',
      'Keys',
      'Indexes',
      'Joins',
      'Transactions',
      'Normalization',
      'Migrations',
    ],
    technologies: ['SQL', 'PostgreSQL'],
    whatGoodLooksLike: ['Explicit schema', 'Integrity', 'Indexed hot paths', 'Migratable'],
    depth: {
      summary: 'PostgreSQL как основной ориентир.',
      detail: 'Моделирование, ключи, индексы, транзакции, миграции — без DBA-сертификации.',
      know: ['Relations', 'Indexes', 'Transactions'],
      able: ['Нарисовать ER', 'Написать миграции', 'Объяснить join'],
      ai: ['Draft schema', 'Suggest indexes', 'Review N+1'],
    },
  },
  {
    id: 'architecture',
    pillar: 'build',
    title: 'Architecture',
    short: 'Boundaries · trade-offs',
    why: 'Архитектура — про зависимости и эволюцию, а не про коллекцию patterns.',
    aiLeverage: 'Compare options, draw boundaries, stress-test coupling — human chooses.',
    outcome: 'Объясняешь, почему система устроена именно так.',
    topics: [
      'Separation of concerns',
      'Modularity',
      'Coupling',
      'Cohesion',
      'Boundaries',
      'Layers',
      'Scalability',
      'Maintainability',
      'Trade-offs',
    ],
    whatGoodLooksLike: ['Simple', 'Explicit', 'Modular', 'Testable', 'Observable', 'Evolvable'],
    depth: {
      summary: 'Почему слои существуют.',
      detail: 'UI → Application → Domain → Infrastructure → Database и альтернативы.',
      know: ['Boundaries', 'Coupling/cohesion', 'Dependency direction'],
      able: ['Нарисовать слои', 'Назвать trade-offs', 'Упростить систему'],
      ai: ['Options matrix', 'Boundary critique'],
    },
  },
  {
    id: 'qa',
    pillar: 'operate',
    title: 'QA',
    short: 'Think like a tester',
    why: 'Качество — инженерная дисциплина, не бюрократия после merge.',
    aiLeverage: 'Generate scenarios — engineer judges coverage and risk.',
    outcome: 'Строишь mental model: happy / alt / edge / invalid / recovery.',
    topics: [
      'Test design',
      'Functional testing',
      'Regression',
      'Edge cases',
      'Unit',
      'Integration',
      'E2E',
      'Mocks',
      'Test data',
    ],
    whatGoodLooksLike: ['Risk-based', 'Pyramid-aware', 'Reproducible', 'Automated where it pays'],
    depth: {
      summary: 'QA mindset внутри OPERATE.',
      detail: 'Сценарии, пирамида тестов, exploratory и quality gates.',
      know: ['Test levels', 'Edge cases', 'Assertions'],
      able: ['Написать unit/integration/E2E', 'Составить matrix сценариев'],
      ai: ['Generate cases', 'Suggest fixtures', 'Never skip human review'],
    },
  },
  {
    id: 'devops',
    pillar: 'operate',
    title: 'DevOps',
    short: 'Ship with confidence',
    why: '«Works on my machine» — red flag. Инженер доводит до среды и наблюдаемости.',
    aiLeverage: 'Draft Dockerfiles/CI — verify secrets, envs, and rollback path.',
    outcome: 'Собрать CI, контейнер и деплой небольшого продукта.',
    topics: [
      'Git',
      'CI/CD',
      'Docker',
      'Environments',
      'Secrets',
      'Logging',
      'Monitoring',
      'Cloud map',
    ],
    technologies: ['Git', 'Docker', 'CI/CD', 'AWS concepts'],
    whatGoodLooksLike: ['Reproducible builds', 'Safe secrets', 'Observable deploys'],
    depth: {
      summary: 'Доставка и среды.',
      detail:
        'Git → build → lint → test → deploy; Docker; staging/prod; cloud map без сертификации.',
      know: ['Pipeline stages', 'Containers', 'Env/secrets'],
      able: ['Написать Dockerfile', 'Настроить CI', 'Задеплоить'],
      ai: ['Draft CI', 'Explain failures', 'Review Dockerfile'],
    },
  },
  {
    id: 'security',
    pillar: 'operate',
    title: 'Security',
    short: 'Think like an attacker',
    why: 'Security — не afterthought. Trust boundaries проходят через весь стек.',
    aiLeverage: 'Threat prompts, checklist reviews — never paste secrets into prompts.',
    outcome: 'Проводишь базовый security review небольшого продукта.',
    topics: [
      'Authentication',
      'Authorization',
      'Secrets',
      'HTTPS',
      'Validation',
      'OWASP mindset',
      'XSS',
      'CSRF',
      'SQLi',
      'CORS',
    ],
    whatGoodLooksLike: [
      'Least privilege',
      'Validated input',
      'No secrets in repo',
      'HTTPS everywhere',
    ],
    depth: {
      summary: 'Security across the stack.',
      detail: 'INPUT → TRUST? → VALIDATE → SANITIZE → AUTHORIZE → EXECUTE.',
      know: ['Authn/Authz', 'Common vulns', 'Secret hygiene'],
      able: ['Threat-model MVP', 'Fix XSS/CSRF class issues', 'Review deps'],
      ai: ['Checklist', 'Explain attack paths', 'Never trust generated auth blindly'],
    },
  },
  {
    id: 'performance',
    pillar: 'operate',
    title: 'Performance',
    short: 'Measure → change → measure',
    why: 'Never optimize blindly. Сначала bottleneck, потом гипотеза.',
    aiLeverage: 'Hypotheses and profiling plans — numbers decide.',
    outcome: 'Умеешь измерить, найти узкое место и проверить изменение.',
    topics: [
      'Core Web Vitals',
      'Bundle size',
      'Caching',
      'N+1',
      'Latency',
      'Throughput',
      'Profiling',
    ],
    whatGoodLooksLike: ['Measured', 'Hypothesis-driven', 'User-visible wins'],
    depth: {
      summary: 'Performance loop.',
      detail: 'Measure → bottleneck → hypothesis → change → measure again.',
      know: ['CWV', 'Backend latency drivers', 'Cache invalidation'],
      able: ['Профилировать', 'Убрать N+1', 'Улучшить LCP/INP'],
      ai: ['Suggest experiments', 'Interpret traces'],
    },
  },
] as const;

export const domainById = Object.fromEntries(
  foundationDomains.map((domain) => [domain.id, domain]),
) as Readonly<Record<string, Domain>>;
