import type { Mission } from '../types';

export const foundationMissions: readonly Mission[] = [
  {
    id: 'mission-spec',
    code: 'MISSION 01',
    title: 'Превратить идею в техническую спецификацию',
    kind: 'mission',
    month: 1,
    objective:
      'Превратить абстрактную идею в структурированную техническую задачу.',
    understand: [
      'Формулировка проблемы',
      'Ограничения',
      'Assumptions',
      'Срез MVP',
    ],
    build: [
      'One-pager',
      'Пользователь + проблема + ценность',
      'Критерии приёмки',
    ],
    aiCanHelp: ['Исследование', 'Черновик структуры', 'Оспорить пробелы'],
    mustVerify: [
      'Проблема реальна',
      'Scope режем осознанно',
      'Критерии проверяемы',
    ],
    doneWhen: ['Спека читаема без автора', 'Есть явный out-of-scope'],
  },
  {
    id: 'boss-01',
    code: 'BOSS 01',
    title: 'Превратить идею в техническую спецификацию',
    kind: 'boss',
    month: 1,
    objective:
      'Закрыть Month 1 boss: идея → техспека без «давайте просто кодить».',
    understand: ['Декомпозиция', 'Trade-offs'],
    build: ['Полный brief технической задачи'],
    aiCanHelp: ['Outline', 'Чеклист вопросов'],
    mustVerify: ['Ты можешь защитить каждое требование'],
    doneWhen: ['Brief готов к мышлению реализации Month 2'],
  },
  {
    id: 'mission-http-trace',
    code: 'MISSION 02',
    title: 'Проследить запрос end-to-end',
    kind: 'mission',
    month: 2,
    objective: 'Проследить HTTP-запрос от UI через сеть до ответа.',
    understand: ['DNS', 'TLS', 'headers', 'status codes', 'кэширование'],
    build: ['Диаграмма одного реального запроса', 'Заметки про cookies/auth'],
    aiCanHelp: ['Объяснить HAR-записи', 'Сравнить status codes'],
    mustVerify: ['Можешь объяснить каждый hop'],
    doneWhen: ['Диаграмма + устный walkthrough'],
  },
  {
    id: 'mission-rest-api',
    code: 'MISSION 03',
    title: 'Собрать REST API',
    kind: 'mission',
    month: 3,
    objective:
      'Создать API небольшого продукта: CRUD, validation, auth, errors, docs.',
    understand: ['Слои', 'Семантика HTTP', 'Validation', 'Auth'],
    build: [
      'Client → API → Server → DB',
      'Реляционные данные',
      'Документация API',
    ],
    aiCanHelp: ['Scaffold routes', 'Черновики validators', 'Генерация OpenAPI'],
    mustVerify: [
      'Объясняешь каждый слой',
      'Ошибки предсказуемы',
      'Auth не «магия»',
    ],
    doneWhen: ['CRUD работает', 'Есть docs', 'Можешь защитить дизайн'],
  },
  {
    id: 'boss-02',
    code: 'BOSS 02',
    title: 'Собрать backend с базой данных',
    kind: 'boss',
    month: 3,
    objective: 'Backend + PostgreSQL + migrations + понятные границы.',
    understand: ['Schema', 'Транзакции', 'Индексы'],
    build: ['Мигрированная schema', 'Service layer', 'Модель ошибок'],
    aiCanHelp: ['Черновики schema', 'Ревью миграций'],
    mustVerify: ['Integrity constraints', 'Нет secrets в репо'],
    doneWhen: ['Демо + объяснение слоёв'],
  },
  {
    id: 'mission-architecture',
    code: 'MISSION 04',
    title: 'Спроектировать архитектуру',
    kind: 'mission',
    month: 4,
    objective:
      'Нарисовать границы UI → Application → Domain → Infrastructure → DB.',
    understand: ['Coupling', 'Cohesion', 'Направление зависимостей'],
    build: ['Диаграмма архитектуры', 'Заметки по trade-offs'],
    aiCanHelp: ['Матрица вариантов', 'Критика границ'],
    mustVerify: ['Почему не проще / не сложнее'],
    doneWhen: ['Диаграмма + 3 trade-offs'],
  },
  {
    id: 'mission-qa-matrix',
    code: 'MISSION 05',
    title: 'Провести полный QA review',
    kind: 'mission',
    month: 4,
    objective:
      'Построить matrix: happy / alt / edge / invalid / unexpected / recovery.',
    understand: ['Пирамида тестов', 'Тестирование по риску'],
    build: ['Matrix сценариев', 'Образцы unit + integration + E2E'],
    aiCanHelp: ['Генерировать кейсы', 'Предложить fixtures'],
    mustVerify: ['Coverage по риску, не по количеству'],
    doneWhen: ['Matrix + минимум один тест каждого уровня'],
  },
  {
    id: 'boss-03',
    code: 'BOSS 03',
    title: 'Спроектировать архитектуру',
    kind: 'boss',
    month: 4,
    objective: 'Защитить архитектуру и QA-модель перед «кодим дальше».',
    understand: ['Границы', 'Стратегия тестов'],
    build: ['Review pack'],
    aiCanHelp: ['Вопросы «адвоката дьявола»'],
    mustVerify: ['Нет «всё зависит от всего»'],
    doneWhen: ['Review pack принят тобой как supervisor'],
  },
  {
    id: 'boss-04',
    code: 'BOSS 04',
    title: 'Провести полный QA review',
    kind: 'boss',
    month: 4,
    objective: 'Полный QA review учебного продукта.',
    understand: ['Регрессия', 'Exploratory'],
    build: ['Список багов с severity', 'Чеклист регрессии'],
    aiCanHelp: ['Расширить edge cases'],
    mustVerify: ['Каждый баг воспроизводим'],
    doneWhen: ['Checklist закрыт или осознанно отложен'],
  },
  {
    id: 'mission-deploy',
    code: 'MISSION 06',
    title: 'Задеплоить production-приложение',
    kind: 'mission',
    month: 5,
    objective: 'Push → build → lint → test → deploy с env/secrets.',
    understand: ['Среды', 'Этапы CI', 'Идея rollback'],
    build: ['CI pipeline', 'Dockerfile или деплой на платформе', 'Карта env'],
    aiCanHelp: ['Черновик CI', 'Объяснить логи сборки'],
    mustVerify: ['Secrets не в git', 'Staging ≠ prod blindly'],
    doneWhen: ['URL в prod-like среде'],
  },
  {
    id: 'mission-security-review',
    code: 'MISSION 07',
    title: 'Security pass: думай как атакующий',
    kind: 'mission',
    month: 5,
    objective:
      'Пройти INPUT → TRUST? → VALIDATE → SANITIZE → AUTHORIZE → EXECUTE.',
    understand: ['OWASP mindset', 'Границы auth'],
    build: ['Threat-заметки', 'Список фиксов'],
    aiCanHelp: ['Чеклист', 'Объяснить vulns'],
    mustVerify: ['Нет secrets в репо', 'Input validated'],
    doneWhen: ['Security-заметки + фиксы по top risks'],
  },
  {
    id: 'boss-05',
    code: 'BOSS 05',
    title: 'Задеплоить production-приложение',
    kind: 'boss',
    month: 5,
    objective: 'Production-like deploy + основы observability.',
    understand: ['Логи', 'Ошибки', 'Базовые метрики'],
    build: ['Задеплоенное приложение', 'Видимость ошибок'],
    aiCanHelp: ['Чеклист мониторинга'],
    mustVerify: ['Можешь увидеть ошибку в проде'],
    doneWhen: ['Deploy + smoke test + доказательство по логам'],
  },
  {
    id: 'mission-foundation-project',
    code: 'MISSION 08',
    title: 'Foundation Project',
    kind: 'mission',
    month: 6,
    objective:
      'Создать небольшой production-like продукт, решающий реальную проблему.',
    understand: ['Полный lifecycle', 'Цикл проверки AI'],
    build: [
      'Продукт + UX',
      'Frontend на Next.js',
      'API + backend + PostgreSQL',
      'Демонстрация REST и GraphQL',
      'Тесты + security + deploy + мониторинг + аналитика',
    ],
    aiCanHelp: [
      'Исследование',
      'Черновик требований',
      'Варианты архитектуры',
      'Реализация',
      'Тесты',
      'Документация',
    ],
    mustVerify: [
      'Понять до принятия',
      'Каждый AI output проверен',
      'Можешь объяснить систему целиком',
    ],
    doneWhen: ['Продукт живёт в prod-like среде', 'Есть демо и postmortem'],
  },
  {
    id: 'boss-final',
    code: 'FINAL BOSS',
    title: 'Собрать цельный продукт',
    kind: 'final',
    month: 6,
    objective: 'Закрыть Phase I Foundation Project end-to-end.',
    understand: ['Расширение ответственности', 'Trust but verify'],
    build: ['Полный срез продукта'],
    aiCanHelp: ['На всём пути — под супервизией'],
    mustVerify: ['Финальная приёмка — человеком'],
    doneWhen: [
      'See → Understand → Build → Verify → Measure → готов к Integrate',
    ],
  },
] as const;

export const missionById = Object.fromEntries(
  foundationMissions.map((mission) => [mission.id, mission]),
) as Readonly<Record<string, Mission>>;
