import type { Mission } from '../types';

export const foundationMissions: readonly Mission[] = [
  {
    id: 'mission-spec',
    code: 'MISSION 01',
    title: 'Turn idea into technical specification',
    kind: 'mission',
    month: 1,
    objective: 'Превратить абстрактную идею в структурированную техническую задачу.',
    understand: ['Problem framing', 'Constraints', 'Assumptions', 'MVP cut'],
    build: ['One-pager', 'User + problem + value', 'Acceptance criteria'],
    aiCanHelp: ['Research', 'Draft structure', 'Challenge gaps'],
    mustVerify: ['Проблема реальна', 'Scope режем осознанно', 'Критерии проверяемы'],
    doneWhen: ['Спека читаема без автора', 'Есть явный out-of-scope'],
  },
  {
    id: 'boss-01',
    code: 'BOSS 01',
    title: 'Turn idea into technical specification',
    kind: 'boss',
    month: 1,
    objective: 'Закрыть Month 1 boss: идея → техспека без «давайте просто кодить».',
    understand: ['Decomposition', 'Trade-offs'],
    build: ['Full tech task brief'],
    aiCanHelp: ['Outline', 'Questions checklist'],
    mustVerify: ['Ты можешь защитить каждое требование'],
    doneWhen: ['Brief готов к Month 2 implementation thinking'],
  },
  {
    id: 'mission-http-trace',
    code: 'MISSION 02',
    title: 'Trace a request end-to-end',
    kind: 'mission',
    month: 2,
    objective: 'Проследить HTTP-запрос от UI через сеть до ответа.',
    understand: ['DNS', 'TLS', 'headers', 'status codes', 'caching'],
    build: ['Diagram of one real request', 'Notes on cookies/auth'],
    aiCanHelp: ['Explain Har entries', 'Compare status codes'],
    mustVerify: ['Можешь объяснить каждый hop'],
    doneWhen: ['Диаграмма + устный walkthrough'],
  },
  {
    id: 'mission-rest-api',
    code: 'MISSION 03',
    title: 'Build a REST API',
    kind: 'mission',
    month: 3,
    objective: 'Создать API небольшого продукта: CRUD, validation, auth, errors, docs.',
    understand: ['Layers', 'HTTP semantics', 'Validation', 'Auth'],
    build: ['Client → API → Server → DB', 'Relational data', 'API docs'],
    aiCanHelp: ['Scaffold routes', 'Draft validators', 'Generate OpenAPI'],
    mustVerify: ['Объясняешь каждый слой', 'Ошибки предсказуемы', 'Auth не «магия»'],
    doneWhen: ['CRUD работает', 'Есть docs', 'Можешь защитить дизайн'],
  },
  {
    id: 'boss-02',
    code: 'BOSS 02',
    title: 'Build backend with database',
    kind: 'boss',
    month: 3,
    objective: 'Backend + PostgreSQL + migrations + понятные границы.',
    understand: ['Schema', 'Transactions', 'Indexes'],
    build: ['Migrated schema', 'Service layer', 'Error model'],
    aiCanHelp: ['Schema drafts', 'Migration review'],
    mustVerify: ['Integrity constraints', 'No secrets in repo'],
    doneWhen: ['Демо + объяснение слоёв'],
  },
  {
    id: 'mission-architecture',
    code: 'MISSION 04',
    title: 'Design architecture',
    kind: 'mission',
    month: 4,
    objective: 'Нарисовать границы UI → Application → Domain → Infrastructure → DB.',
    understand: ['Coupling', 'Cohesion', 'Dependency direction'],
    build: ['Architecture diagram', 'Trade-off notes'],
    aiCanHelp: ['Options matrix', 'Boundary critique'],
    mustVerify: ['Почему не проще / не сложнее'],
    doneWhen: ['Диаграмма + 3 trade-offs'],
  },
  {
    id: 'mission-qa-matrix',
    code: 'MISSION 05',
    title: 'Perform complete QA review',
    kind: 'mission',
    month: 4,
    objective: 'Построить matrix: happy / alt / edge / invalid / unexpected / recovery.',
    understand: ['Test pyramid', 'Risk-based testing'],
    build: ['Scenario matrix', 'Unit + integration + E2E samples'],
    aiCanHelp: ['Generate cases', 'Suggest fixtures'],
    mustVerify: ['Coverage по риску, не по количеству'],
    doneWhen: ['Matrix + минимум один тест каждого уровня'],
  },
  {
    id: 'boss-03',
    code: 'BOSS 03',
    title: 'Design architecture',
    kind: 'boss',
    month: 4,
    objective: 'Защитить архитектуру и QA-модель перед «кодим дальше».',
    understand: ['Boundaries', 'Test strategy'],
    build: ['Review pack'],
    aiCanHelp: ['Devil’s advocate questions'],
    mustVerify: ['Нет «всё зависит от всего»'],
    doneWhen: ['Review pack принят тобой как supervisor'],
  },
  {
    id: 'boss-04',
    code: 'BOSS 04',
    title: 'Perform complete QA review',
    kind: 'boss',
    month: 4,
    objective: 'Полный QA review учебного продукта.',
    understand: ['Regression', 'Exploratory'],
    build: ['Bug list with severity', 'Regression checklist'],
    aiCanHelp: ['Expand edge cases'],
    mustVerify: ['Каждый баг воспроизводим'],
    doneWhen: ['Checklist закрыт или осознанно отложен'],
  },
  {
    id: 'mission-deploy',
    code: 'MISSION 06',
    title: 'Deploy production application',
    kind: 'mission',
    month: 5,
    objective: 'Push → build → lint → test → deploy с env/secrets.',
    understand: ['Environments', 'CI stages', 'Rollback idea'],
    build: ['CI pipeline', 'Dockerfile or platform deploy', 'Env map'],
    aiCanHelp: ['Draft CI', 'Explain build logs'],
    mustVerify: ['Secrets не в git', 'Staging ≠ prod blindly'],
    doneWhen: ['URL в prod-like среде'],
  },
  {
    id: 'mission-security-review',
    code: 'MISSION 07',
    title: 'Security pass: think like an attacker',
    kind: 'mission',
    month: 5,
    objective: 'Пройти INPUT → TRUST? → VALIDATE → SANITIZE → AUTHORIZE → EXECUTE.',
    understand: ['OWASP mindset', 'Auth boundaries'],
    build: ['Threat notes', 'Fix list'],
    aiCanHelp: ['Checklist', 'Explain vulns'],
    mustVerify: ['Нет secrets в репо', 'Input validated'],
    doneWhen: ['Security notes + fixes for top risks'],
  },
  {
    id: 'boss-05',
    code: 'BOSS 05',
    title: 'Deploy production application',
    kind: 'boss',
    month: 5,
    objective: 'Production-like deploy + observability basics.',
    understand: ['Logs', 'Errors', 'Basic metrics'],
    build: ['Deployed app', 'Error visibility'],
    aiCanHelp: ['Monitoring checklist'],
    mustVerify: ['Можешь увидеть ошибку в проде'],
    doneWhen: ['Deploy + smoke test + log proof'],
  },
  {
    id: 'mission-foundation-project',
    code: 'MISSION 08',
    title: 'Foundation Project',
    kind: 'mission',
    month: 6,
    objective: 'Создать небольшой production-like продукт, решающий реальную проблему.',
    understand: ['Full lifecycle', 'AI verification loop'],
    build: [
      'Product + UX',
      'Next.js frontend',
      'API + backend + PostgreSQL',
      'REST and GraphQL demonstration',
      'Tests + security + deploy + monitoring + analytics',
    ],
    aiCanHelp: [
      'Research',
      'Draft requirements',
      'Architecture options',
      'Implementation',
      'Tests',
      'Docs',
    ],
    mustVerify: [
      'Understand before accept',
      'Каждый AI output проверен',
      'Можешь объяснить систему целиком',
    ],
    doneWhen: ['Продукт живёт в prod-like среде', 'Есть демо и postmortem'],
  },
  {
    id: 'boss-final',
    code: 'FINAL BOSS',
    title: 'Build complete product',
    kind: 'final',
    month: 6,
    objective: 'Закрыть Phase I Foundation Project end-to-end.',
    understand: ['Responsibility expansion', 'Trust but verify'],
    build: ['Complete product slice'],
    aiCanHelp: ['Throughout — under supervision'],
    mustVerify: ['Final acceptance is human'],
    doneWhen: ['See → Understand → Build → Verify → Measure → ready to Integrate'],
  },
] as const;

export const missionById = Object.fromEntries(
  foundationMissions.map((mission) => [mission.id, mission]),
) as Readonly<Record<string, Mission>>;
