import type { Month } from '../types';

export const foundationMonths: readonly Month[] = [
  {
    id: 'month-1',
    number: 1,
    title: 'Инженерное мышление',
    goal: 'Перестать смотреть на разработку как на написание кода.',
    themes: [
      {
        title: 'Решение проблем',
        topics: [
          'формулировка проблемы',
          'декомпозиция',
          'ограничения',
          'assumptions',
          'root cause',
        ],
      },
      {
        title: 'Продуктовое мышление',
        topics: [
          'пользователь',
          'проблема',
          'ценность',
          'требования',
          'MVP',
          'trade-offs',
        ],
      },
      {
        title: 'Техническое мышление',
        topics: [
          'системы',
          'компоненты',
          'зависимости',
          'интерфейсы',
          'поток данных',
        ],
      },
      {
        title: 'AI',
        topics: [
          'prompting',
          'контекст',
          'проверка',
          'hallucinations',
          'исследование с AI',
          'обучение с AI',
        ],
      },
      {
        title: 'Git',
        topics: [
          'ветки',
          'коммиты',
          'merge',
          'pull requests',
          'история',
          'rollback',
        ],
      },
    ],
    output:
      'Взять абстрактную идею и превратить её в структурированную техническую задачу.',
    missionIds: ['mission-spec'],
    bossMissionId: 'boss-01',
  },
  {
    id: 'month-2',
    number: 2,
    title: 'Основы веба и приложений',
    goal: 'Понять, что происходит между браузером, сервером, сетью и приложением.',
    themes: [
      {
        title: 'HTTP',
        topics: [
          'request/response',
          'methods',
          'headers',
          'status codes',
          'cookies',
          'кэширование',
          'основы auth',
        ],
      },
      {
        title: 'Браузер',
        topics: ['рендеринг', 'DOM', 'CSS', 'JS runtime', 'сеть', 'storage'],
      },
      {
        title: 'Сеть',
        topics: ['DNS', 'основы TCP/IP', 'TLS', 'CDN', 'proxy'],
      },
      {
        title: 'Frontend (глубина)',
        topics: [
          'JavaScript',
          'TypeScript',
          'React',
          'Next.js',
          'модели рендеринга',
          'state',
          'data fetching',
          'performance',
        ],
      },
    ],
    output:
      'Объяснить путь запроса от UI до сети и обратно — без магии фреймворка.',
    missionIds: ['mission-http-trace'],
  },
  {
    id: 'month-3',
    number: 3,
    title: 'Backend + API + база данных',
    goal: 'Собрать рабочую вертикаль Client → API → Server → Database.',
    themes: [
      {
        title: 'Backend',
        topics: [
          'сервер',
          'runtime',
          'routes',
          'services',
          'validation',
          'ошибки',
          'authentication',
          'authorization',
        ],
      },
      {
        title: 'REST',
        topics: [
          'моделирование ресурсов',
          'endpoints',
          'пагинация',
          'фильтрация',
          'сортировка',
          'версионирование',
        ],
      },
      {
        title: 'GraphQL',
        topics: ['schema', 'query', 'mutation', 'resolver', 'trade-offs'],
      },
      {
        title: 'PostgreSQL',
        topics: [
          'таблицы',
          'связи',
          'ключи',
          'индексы',
          'joins',
          'транзакции',
          'нормализация',
          'миграции',
        ],
      },
      {
        title: 'Кэширование',
        topics: [
          'зачем кэш',
          'инвалидация',
          'кэш client/server',
          'концепт Redis',
        ],
      },
    ],
    output: 'Объяснить зачем существует каждый слой своей учебной системы.',
    missionIds: ['mission-rest-api'],
    bossMissionId: 'boss-02',
  },
  {
    id: 'month-4',
    number: 4,
    title: 'Архитектура + UX/UI + QA',
    goal: 'Соединить техническую и пользовательскую стороны продукта.',
    themes: [
      {
        title: 'Архитектура',
        topics: [
          'SoC',
          'модульность',
          'coupling',
          'cohesion',
          'границы',
          'слои',
          'trade-offs',
        ],
      },
      {
        title: 'UX/UI',
        topics: [
          'user flow',
          'когнитивная нагрузка',
          'иерархия',
          'design systems',
          'accessibility',
          'состояния',
        ],
      },
      {
        title: 'QA',
        topics: [
          'тест-кейсы',
          'edge cases',
          'unit',
          'integration',
          'E2E',
          'exploratory',
          'mocks',
        ],
      },
    ],
    output: 'Спроектировать границы системы и проверить её глазами QA.',
    missionIds: ['mission-architecture', 'mission-qa-matrix'],
    bossMissionId: 'boss-03',
  },
  {
    id: 'month-5',
    number: 5,
    title: 'DevOps + безопасность + performance',
    goal: 'Доставить продукт безопасно и измеримо.',
    themes: [
      {
        title: 'DevOps',
        topics: [
          'Docker',
          'CI/CD',
          'среды',
          'secrets',
          'карта cloud',
          'мониторинг',
        ],
      },
      {
        title: 'Безопасность',
        topics: [
          'auth',
          'sessions/tokens',
          'OWASP mindset',
          'XSS/CSRF/SQLi',
          'CORS',
          'уязвимости зависимостей',
        ],
      },
      {
        title: 'Performance',
        topics: [
          'CWV',
          'бандл',
          'кэширование',
          'N+1',
          'latency',
          'цикл измерения',
        ],
      },
    ],
    output: 'Задеплоить, проверить security basics и измерить узкие места.',
    missionIds: ['mission-deploy', 'mission-security-review'],
    bossMissionId: 'boss-05',
  },
  {
    id: 'month-6',
    number: 6,
    title: 'Полная продуктовая инженерия',
    goal: 'Пройти полный lifecycle одной небольшой продуктовой идеи.',
    themes: [
      {
        title: 'Продукт end-to-end',
        topics: [
          'проблема',
          'продукт',
          'требования',
          'UX',
          'архитектура',
          'frontend',
          'backend',
          'база данных',
          'API',
          'auth',
          'тестирование',
          'безопасность',
          'performance',
          'деплой',
          'мониторинг',
          'аналитика',
        ],
      },
    ],
    output:
      'Самостоятельно создать небольшой production-like продукт с AI как помощником.',
    missionIds: ['mission-foundation-project'],
    bossMissionId: 'boss-final',
  },
] as const;
