import type { Skill } from '../types';

/** Skill tree nodes — statuses are illustrative roadmap states, not personal scores. */
export const foundationSkills: readonly Skill[] = [
  {
    id: 'problem-framing',
    title: 'Problem Framing',
    description: 'Сформулировать проблему, ограничения и assumptions.',
    level: 'foundation',
    domains: ['product', 'analysis'],
    topics: ['problem', 'constraints', 'assumptions'],
    aiApplications: ['Challenge framing', 'Surface hidden assumptions'],
    missionId: 'mission-spec',
  },
  {
    id: 'product-mvp',
    title: 'MVP Thinking',
    description: 'Вырезать минимальный ценный срез.',
    level: 'foundation',
    domains: ['product'],
    prerequisites: ['problem-framing'],
    topics: ['MVP', 'prioritization', 'trade-offs'],
    aiApplications: ['Suggest cuts', 'Stress-test scope'],
  },
  {
    id: 'http-fundamentals',
    title: 'HTTP Fundamentals',
    description: 'Request/response, methods, status, headers.',
    level: 'foundation',
    domains: ['api', 'frontend', 'backend'],
    topics: ['HTTP', 'status codes', 'headers'],
    missionId: 'mission-http-trace',
  },
  {
    id: 'frontend-depth',
    title: 'Frontend Depth',
    description: 'TS/React/Next как глубокая специализация.',
    level: 'advanced',
    domains: ['frontend'],
    prerequisites: ['http-fundamentals'],
    topics: ['React', 'Next.js', 'state', 'fetching'],
    technologies: ['TypeScript', 'React', 'Next.js'],
  },
  {
    id: 'rest-design',
    title: 'REST Design',
    description: 'Ресурсы, семантика, пагинация, ошибки.',
    level: 'intermediate',
    domains: ['api', 'backend'],
    prerequisites: ['http-fundamentals'],
    topics: ['resources', 'pagination', 'errors'],
    missionId: 'mission-rest-api',
  },
  {
    id: 'graphql-basics',
    title: 'GraphQL Basics',
    description: 'Schema, query/mutation, trade-offs vs REST.',
    level: 'intermediate',
    domains: ['api'],
    prerequisites: ['rest-design'],
    topics: ['schema', 'resolvers', 'trade-offs'],
  },
  {
    id: 'postgres-modelling',
    title: 'PostgreSQL Modelling',
    description: 'Таблицы, связи, ключи, миграции.',
    level: 'intermediate',
    domains: ['database'],
    prerequisites: ['rest-design'],
    topics: ['schema', 'indexes', 'migrations'],
    technologies: ['PostgreSQL'],
  },
  {
    id: 'system-boundaries',
    title: 'System Boundaries',
    description: 'Слои, coupling, cohesion, dependency direction.',
    level: 'intermediate',
    domains: ['architecture'],
    prerequisites: ['postgres-modelling', 'frontend-depth'],
    topics: ['layers', 'boundaries', 'trade-offs'],
    missionId: 'mission-architecture',
  },
  {
    id: 'ux-evaluation',
    title: 'UX Evaluation',
    description: 'Отличать ясный интерфейс от шума.',
    level: 'foundation',
    domains: ['ux-ui'],
    topics: ['flows', 'hierarchy', 'a11y'],
  },
  {
    id: 'qa-mindset',
    title: 'QA Mindset',
    description: 'Happy / alt / edge / invalid / recovery.',
    level: 'foundation',
    domains: ['qa'],
    prerequisites: ['system-boundaries'],
    topics: ['scenarios', 'pyramid', 'regression'],
    missionId: 'mission-qa-matrix',
  },
  {
    id: 'ci-cd-basics',
    title: 'CI/CD Basics',
    description: 'Push → build → lint → test → deploy.',
    level: 'intermediate',
    domains: ['devops'],
    prerequisites: ['qa-mindset'],
    topics: ['Docker', 'CI', 'environments'],
    missionId: 'mission-deploy',
  },
  {
    id: 'security-basics',
    title: 'Security Basics',
    description: 'Trust boundaries и OWASP mindset.',
    level: 'intermediate',
    domains: ['security'],
    prerequisites: ['ci-cd-basics'],
    topics: ['auth', 'validation', 'XSS/CSRF/SQLi'],
    missionId: 'mission-security-review',
  },
  {
    id: 'performance-loop',
    title: 'Performance Loop',
    description: 'Measure before optimizing.',
    level: 'intermediate',
    domains: ['performance'],
    prerequisites: ['frontend-depth', 'postgres-modelling'],
    topics: ['CWV', 'profiling', 'N+1'],
  },
  {
    id: 'ai-tutor',
    title: 'AI as Tutor',
    description: 'Обучение, сравнение, исследование с проверкой.',
    level: 'foundation',
    domains: ['product', 'analysis'],
    topics: ['prompting', 'hallucinations', 'verification'],
  },
  {
    id: 'ai-assistant',
    title: 'AI Coding Assistant',
    description: 'Код и тесты под human review.',
    level: 'foundation',
    domains: ['frontend', 'backend'],
    prerequisites: ['ai-tutor'],
    topics: ['generate', 'refactor', 'explain'],
  },
  {
    id: 'ai-agent-supervise',
    title: 'Agent Supervision',
    description: 'Define → Delegate → Review → Verify → Approve.',
    level: 'advanced',
    domains: ['architecture'],
    prerequisites: ['ai-assistant', 'qa-mindset'],
    topics: ['task brief', 'verification loop'],
    missionId: 'mission-foundation-project',
  },
] as const;

/** Illustrative default statuses for the atlas skill tree (roadmap progress, not grading). */
export const skillStatusById: Readonly<Record<string, string>> = {
  'problem-framing': 'completed',
  'product-mvp': 'completed',
  'http-fundamentals': 'foundation',
  'frontend-depth': 'in_progress',
  'rest-design': 'available',
  'graphql-basics': 'locked',
  'postgres-modelling': 'available',
  'system-boundaries': 'locked',
  'ux-evaluation': 'available',
  'qa-mindset': 'locked',
  'ci-cd-basics': 'locked',
  'security-basics': 'locked',
  'performance-loop': 'locked',
  'ai-tutor': 'foundation',
  'ai-assistant': 'available',
  'ai-agent-supervise': 'locked',
};
