import type { Skill } from '../types';

/** Skill tree nodes — statuses are illustrative roadmap states, not personal scores. */
export const foundationSkills: readonly Skill[] = [
  {
    id: 'problem-framing',
    title: 'Формулировка проблемы',
    description: 'Сформулировать проблему, ограничения и assumptions.',
    level: 'foundation',
    domains: ['product', 'analysis'],
    topics: ['проблема', 'ограничения', 'assumptions'],
    aiApplications: ['Оспорить framing', 'Вытащить скрытые assumptions'],
    missionId: 'mission-spec',
  },
  {
    id: 'product-mvp',
    title: 'Мышление MVP',
    description: 'Вырезать минимальный ценный срез.',
    level: 'foundation',
    domains: ['product'],
    prerequisites: ['problem-framing'],
    topics: ['MVP', 'приоритизация', 'trade-offs'],
    aiApplications: ['Предложить срезы', 'Стресс-тест scope'],
  },
  {
    id: 'http-fundamentals',
    title: 'Основы HTTP',
    description: 'Request/response, methods, status, headers.',
    level: 'foundation',
    domains: ['api', 'frontend', 'backend'],
    topics: ['HTTP', 'status codes', 'headers'],
    missionId: 'mission-http-trace',
  },
  {
    id: 'frontend-depth',
    title: 'Глубина Frontend',
    description: 'TS/React/Next как глубокая специализация.',
    level: 'advanced',
    domains: ['frontend'],
    prerequisites: ['http-fundamentals'],
    topics: ['React', 'Next.js', 'state', 'fetching'],
    technologies: ['TypeScript', 'React', 'Next.js'],
  },
  {
    id: 'rest-design',
    title: 'Дизайн REST',
    description: 'Ресурсы, семантика, пагинация, ошибки.',
    level: 'intermediate',
    domains: ['api', 'backend'],
    prerequisites: ['http-fundamentals'],
    topics: ['ресурсы', 'пагинация', 'ошибки'],
    missionId: 'mission-rest-api',
  },
  {
    id: 'graphql-basics',
    title: 'Основы GraphQL',
    description: 'Schema, query/mutation, trade-offs vs REST.',
    level: 'intermediate',
    domains: ['api'],
    prerequisites: ['rest-design'],
    topics: ['schema', 'resolvers', 'trade-offs'],
  },
  {
    id: 'postgres-modelling',
    title: 'Моделирование PostgreSQL',
    description: 'Таблицы, связи, ключи, миграции.',
    level: 'intermediate',
    domains: ['database'],
    prerequisites: ['rest-design'],
    topics: ['schema', 'индексы', 'миграции'],
    technologies: ['PostgreSQL'],
  },
  {
    id: 'system-boundaries',
    title: 'Границы системы',
    description: 'Слои, coupling, cohesion, направление зависимостей.',
    level: 'intermediate',
    domains: ['architecture'],
    prerequisites: ['postgres-modelling', 'frontend-depth'],
    topics: ['слои', 'границы', 'trade-offs'],
    missionId: 'mission-architecture',
  },
  {
    id: 'ux-evaluation',
    title: 'Оценка UX',
    description: 'Отличать ясный интерфейс от шума.',
    level: 'foundation',
    domains: ['ux-ui'],
    topics: ['flows', 'иерархия', 'a11y'],
  },
  {
    id: 'qa-mindset',
    title: 'Мышление QA',
    description: 'Happy / alt / edge / invalid / recovery.',
    level: 'foundation',
    domains: ['qa'],
    prerequisites: ['system-boundaries'],
    topics: ['сценарии', 'пирамида', 'регрессия'],
    missionId: 'mission-qa-matrix',
  },
  {
    id: 'ci-cd-basics',
    title: 'Основы CI/CD',
    description: 'Push → build → lint → test → deploy.',
    level: 'intermediate',
    domains: ['devops'],
    prerequisites: ['qa-mindset'],
    topics: ['Docker', 'CI', 'среды'],
    missionId: 'mission-deploy',
  },
  {
    id: 'security-basics',
    title: 'Основы безопасности',
    description: 'Trust boundaries и OWASP mindset.',
    level: 'intermediate',
    domains: ['security'],
    prerequisites: ['ci-cd-basics'],
    topics: ['auth', 'validation', 'XSS/CSRF/SQLi'],
    missionId: 'mission-security-review',
  },
  {
    id: 'performance-loop',
    title: 'Цикл performance',
    description: 'Измерь до оптимизации.',
    level: 'intermediate',
    domains: ['performance'],
    prerequisites: ['frontend-depth', 'postgres-modelling'],
    topics: ['CWV', 'профилирование', 'N+1'],
  },
  {
    id: 'ai-tutor',
    title: 'AI как наставник',
    description: 'Обучение, сравнение, исследование с проверкой.',
    level: 'foundation',
    domains: ['product', 'analysis'],
    topics: ['prompting', 'hallucinations', 'verification'],
  },
  {
    id: 'ai-assistant',
    title: 'AI как coding assistant',
    description: 'Код и тесты под human review.',
    level: 'foundation',
    domains: ['frontend', 'backend'],
    prerequisites: ['ai-tutor'],
    topics: ['генерация', 'рефакторинг', 'объяснение'],
  },
  {
    id: 'ai-agent-supervise',
    title: 'Супервизия агента',
    description: 'Define → Delegate → Review → Verify → Approve.',
    level: 'advanced',
    domains: ['architecture'],
    prerequisites: ['ai-assistant', 'qa-mindset'],
    topics: ['brief задачи', 'цикл проверки'],
    missionId: 'mission-foundation-project',
  },
] as const;

/** Illustrative default statuses for the atlas skill tree (roadmap progress, not grading). */
export const skillStatusById: Readonly<Record<string, string>> = {
  'problem-framing': 'completed',
  'product-mvp': 'completed',
  'http-fundamentals': 'foundation',
  'frontend-depth': 'in_progress',
  'rest-design': 'available',
  'graphql-basics': 'locked',
  'postgres-modelling': 'available',
  'system-boundaries': 'locked',
  'ux-evaluation': 'available',
  'qa-mindset': 'locked',
  'ci-cd-basics': 'locked',
  'security-basics': 'locked',
  'performance-loop': 'locked',
  'ai-tutor': 'foundation',
  'ai-assistant': 'available',
  'ai-agent-supervise': 'locked',
};
